
Microsoft Visual Studio Solution File, Format Version 10.00
# Visual C++ Express 2008
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aadetect", "aadetect.vcproj", "{ACBBBBDF-AAAC-47F5-A1B3-3EF1D498186F}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aagpio", "aagpio.vcproj", "{43B8D1E4-9A12-4BA9-98DB-9722FC1BD093}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aai2c_eeprom", "aai2c_eeprom.vcproj", "{8BEA0ED0-0E29-4BDA-B8B1-98AD211B72C0}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aai2c_file", "aai2c_file.vcproj", "{15BAB1EF-500C-44FA-9BA7-F9CEDCD11710}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aai2c_slave", "aai2c_slave.vcproj", "{C01A5C22-16AA-4052-9286-241D56EBCD45}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aalights", "aalights.vcproj", "{076B8C63-13EA-40A6-A738-4E1885D20D46}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aaspi_eeprom", "aaspi_eeprom.vcproj", "{F0C42B57-2884-4C4E-830D-02BDB8F19D02}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aaspi_file", "aaspi_file.vcproj", "{C9B45870-4328-4A4F-ABCE-95351F5DC92C}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "aaspi_slave", "aaspi_slave.vcproj", "{0A8203FC-52AD-4564-80CF-822092B39237}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Release|@arch_msvc@ = Release|@arch_msvc@
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{ACBBBBDF-AAAC-47F5-A1B3-3EF1D498186F}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{ACBBBBDF-AAAC-47F5-A1B3-3EF1D498186F}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{43B8D1E4-9A12-4BA9-98DB-9722FC1BD093}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{43B8D1E4-9A12-4BA9-98DB-9722FC1BD093}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{8BEA0ED0-0E29-4BDA-B8B1-98AD211B72C0}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{8BEA0ED0-0E29-4BDA-B8B1-98AD211B72C0}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{15BAB1EF-500C-44FA-9BA7-F9CEDCD11710}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{15BAB1EF-500C-44FA-9BA7-F9CEDCD11710}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{C01A5C22-16AA-4052-9286-241D56EBCD45}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{C01A5C22-16AA-4052-9286-241D56EBCD45}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{076B8C63-13EA-40A6-A738-4E1885D20D46}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{076B8C63-13EA-40A6-A738-4E1885D20D46}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{F0C42B57-2884-4C4E-830D-02BDB8F19D02}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{F0C42B57-2884-4C4E-830D-02BDB8F19D02}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{C9B45870-4328-4A4F-ABCE-95351F5DC92C}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{C9B45870-4328-4A4F-ABCE-95351F5DC92C}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
		{0A8203FC-52AD-4564-80CF-822092B39237}.Release|@arch_msvc@.ActiveCfg = Release|@arch_msvc@
		{0A8203FC-52AD-4564-80CF-822092B39237}.Release|@arch_msvc@.Build.0 = Release|@arch_msvc@
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
